language: python
python:
  - "2.7"
  #- "3.2" # Not supported
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install pytest-cov
script: pytest --cov=./
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then codecov; fi
