language: python
python:
  # "2.6" not supported
  - "2.7"
  # "3.2" not supported
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
script: pytest
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then coveralls; fi
